### ISSUE TITLE
iOS build fails on build.phonegap.com

### ISSUE THREAD

**Issue by ghost** [pmwisdom/cordova-background-geolocation-services#14]
Not sure if this is the correct place to post, but I'm trying to build an app with this plugin using build.phonegap.com and it's working great on android but I'm getting the following error for iOS. 

```
** BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64 /project/ProjectPulse/Plugins/org.flybuy.cordova.background-location-services/CDVBackgroundLocationServices.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

With a bunch of "undeclared type" errors like the below

```
/project/MyProject/Plugins/org.flybuy.cordova.background-location-services/CDVBackgroundLocationServices.swift:20:29: error: use of undeclared type 'UIWebView'
var LocationServiceWebView: UIWebView?
```

Relevant lines in config.xml (I think)

```
<preference name="deployment-target" value="7.0" />
<plugin name="cordova-background-location-services" spec="~1.0.0" />
```

From what I can gather from some googling this seems to be related to bridging headers but I have no experience with Swift so am not sure how to go about fixing it. Any help would be greatly appreciated. If this isn't the correct place to ask about this would it be possible to point me in the right direction?

**Comment by pmwisdom** [comment]
Hey @createdincode that should be fixed as of https://github.com/pmwisdom/cordova-background-geolocation-services/pull/13. Try the most recent version.

**Comment by ghost** [comment]
Hi @pmwisdom thanks for the tip. I've just tried again using the following

`<plugin name="org.flybuy.cordova.background-location-services" spec="https://github.com/pmwisdom/cordova-background-geolocation-services.git" />`

and unfortunately still get errors - I've attached the log below if that helps
[build.txt](https://github.com/pmwisdom/cordova-background-geolocation-services/files/200646/build.txt)

**Comment by pmwisdom** [comment]
Hey @createdincode I believe it has to do with the swift hook. I just commited a new version if you want to give it another try.

**Comment by ghost** [comment]
Hi @pmwisdom thanks for the help on this:

Unfortunately I'm still getting 

```
The following build commands failed:
CompileSwift normal arm64 /project/ProjectPulse/Plugins/org.flybuy.cordova.background-location-services/CDVBackgroundLocationServices.swift
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
```

**Comment by pmwisdom** [comment]
If I've got time in the next few days I'll try it out on phonegap build, but I've never used it so it might take a bit of time.

**Comment by ghost** [comment]
No problem, thanks for taking a look

**Comment by ivanssa** [comment]
Hello I would first like to congratulate the work, I am also facing the same problem when trying to compile my app using the build phonegap in my case the error that appears in IOS is:

Log Error

```
check dependencies
Swift is unavailable on iOS Earlier than 7.0; PLEASE SET IPHONEOS_DEPLOYMENT_TARGET to 7.0 or later (currently it is '6.0').
warning: skipping file '/project/com.google.android.gms:play-services-location:+' (unexpected file type 'file' in Frameworks & Libraries build phase)
warning: skipping file '/project/com.google.android.gms:play-services-location:+' (unexpected file type 'file' in Frameworks & Libraries build phase)

** BUILD FAILED **


The Following build commands failed:
check dependencies
(1 failure)
```

Could anyone help?

**Comment by ghost** [comment]
Hi @ivanssa 

It looks to me like you need the following line in your config.xml file to make sure build.phonegap.com builds for ios 7+

`<preference name="deployment-target" value="7.0" />`

**Comment by ivanssa** [comment]
@createdincode Thank you, we're almost there, I'm still looking for the solution, after I made the change and added `<preference name = "deployment-target" value = "7.0" />` you said I got an error like this:

```
** BUILD FAILED **

The Following build commands failed:
CompileSwift regular arm64/project/MyApp/Plugins/org.flybuy.cordova.background-location-services/CDVBackgroundLocationServices.swift
Normal CompileSwiftSources arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

```

after researching I found a solution that can compile to upgrade to the new version of phonegap added `<preference name = "phonegap-version" value = "cli-6.0.0" />` I was happy thinking that he had found the solution, but unfortunately I downloaded the app installed on iOS but when I try to open it closes quickly and does not open in any way to test compile just tried removing plugin and the application opened normally, so I think it is a problem with ios version of this plugin. :-(

@pmwisdom you could help us in this matter?

**Comment by ghost** [comment]
The inappbrowser plugin wasn't necessary for me but it appears changing the phonegap version from 5.4 -> 6 fixes it for me too.

Thanks for posting your fix.

@pmwisdom looks like it was an issue with my config.xml as @ivanssa solution works for me too. Thanks for the time you've put in to helping me out.

**Comment by ivanssa** [comment]
@createdincode I'm still having problems with the error when trying to open the app on ios it opens and closes quickly, you could post an example of your config.xml so I can check which is giving this error?

**Comment by pmwisdom** [comment]
@creatincode that's good to know for phone gap build, I will put that in the readme for people in the future. Thanks for posting your fix.

**Comment by pmwisdom** [comment]
Thanks for checking this out all. I will put that in the README.

**Comment by ghost** [comment]
@ivanssa I have the same issue unfortunately so I won't be much help - unfortunately I don't have great access to ios devices so testing it takes me a while. If I find a solution I'll post it here
